-- Add new equipment and environment fields to properties table
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "eq_counter_kitchen"      BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "eq_cupboard"             BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "eq_pantry"               BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "eq_touchless_faucet"     BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "eq_unit_bath"            BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "eq_separate_bath_toilet" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "eq_double_wash"          BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "eq_laundry_space"        BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "eq_laundry_outdoor"      BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "eq_toilet_count"         INTEGER;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "eq_washlet_all"          BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "eq_shoe_closet"          BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "eq_trunk_room"           BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "eq_roof_storage"         BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "eq_all_room_storage"     BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "eq_high_insulation"      BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "eq_long_quality"         BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "eq_zeh"                  BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "eq_storage_battery"      BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "eq_ev_charger"           BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "eq_double_glazing"       BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "eq_ventilation"          BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "eq_crime_prevention_glass" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "eq_electronic_lock"      BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "eq_security_light"       BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "eq_parking_roofed"       BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "eq_parking_2cars"        BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "eq_electric_shutter"     BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "eq_bicycle_count"        INTEGER;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "eq_floor_heating_all"    BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "eq_ceiling_height"       DOUBLE PRECISION;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "eq_barrier_free"         BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "eq_elevator_private"     BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "eq_optical_fiber"        BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "eq_cable_tv"             BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "eq_interphone_video"     BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "eq_terrace"              BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "eq_roof_balcony"         BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "eq_patio"                BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "eq_wood_deck"            BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "eq_reformed"             BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "eq_renovated"            BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "eq_reform_year"          INTEGER;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "eq_new_kitchen"          BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "eq_new_bath"             BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "eq_new_toilet"           BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "eq_new_floor"            BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "eq_new_wall"             BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "eq_earthquake_resistant" TEXT;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "eq_seismic_isolation"    BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "eq_vibration_control"    BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "env_elementary_school"   TEXT;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "env_junior_high_school"  TEXT;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "env_supermarket"         TEXT;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "env_hospital"            TEXT;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "env_park"                TEXT;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "env_disaster_risk"       TEXT;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "env_crime_level"         TEXT;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "env_noise_level"         TEXT;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "env_sunlight"            TEXT;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "env_view"                TEXT;
