// src/lib/propertyFeatures.ts

export type Portal = 'S' | 'A' | 'Y';

export interface FeatureItem {
  id: string;
  label: string;
  portals: Portal[];
}

export interface FeatureCategory {
  id: string;
  label: string;
  items: FeatureItem[];
}

export const PROPERTY_FEATURES: FeatureCategory[] = [
  {
    id: 'indoor',
    label: '室内設備・仕様',
    items: [
      { id: 'barrier_free', label: 'バリアフリー', portals: ['S','A','Y'] },
      { id: 'high_ceiling', label: '天井高2.5m以上', portals: ['S','A'] },
      { id: 'floor_heating', label: '床暖房', portals: ['S','A','Y'] },
      { id: 'flooring', label: 'フローリング', portals: [] },
      { id: 'all_room_flooring', label: '全居室フローリング', portals: ['S','A'] },
      { id: 'living_stairs', label: 'リビング階段', portals: ['S','Y'] },
      { id: 'natural_material', label: '自然素材', portals: ['S'] },
      { id: 'fire_alarm', label: '火災警報器（報知機）', portals: ['A'] },
      { id: 'lighting', label: '照明器具', portals: ['A'] },
      { id: 'kerosene', label: '灯油', portals: [] },
      { id: 'ff_heating', label: 'FF暖房', portals: ['A'] },
      { id: 'central_heating', label: 'セントラル', portals: ['A'] },
      { id: 'air_con', label: 'エアコン', portals: ['A'] },
      { id: 'ventilation_24h', label: '24時間換気システム', portals: ['A','Y'] },
      { id: 'shutter', label: 'シャッター雨戸', portals: ['A'] },
      { id: 'bay_window', label: '出窓', portals: ['A'] },
      { id: 'hot_water', label: '給湯', portals: [] },
      { id: 'sunken_kotatsu', label: '掘ごたつ', portals: ['A'] },
      { id: 'led_lighting', label: 'LED照明', portals: [] },
      { id: 'insulation_sash', label: '断熱サッシ', portals: [] },
      { id: 'furnished', label: '家具付', portals: [] },
      { id: 'double_glazing_all', label: '全居室複層ガラスか複層サッシ', portals: ['S'] },
      { id: 'multimedia_outlet', label: 'マルチメディアコンセント', portals: ['A'] },
      { id: 'indirect_lighting', label: '間接照明', portals: ['A'] },
      { id: 'motion_sensor_light', label: '人感センサー付照明', portals: ['A'] },
      { id: 'downlight', label: 'ダウンライト', portals: ['A'] },
      { id: 'footlight', label: 'フットライト', portals: ['A'] },
      { id: 'indoor_clothesline', label: '室内物干し', portals: ['A'] },
      { id: 'cushion_floor', label: 'クッションフロア', portals: ['A'] },
      { id: 'aircon_2plus', label: 'エアコン2台以上', portals: ['A'] },
      { id: 'builtin_aircon', label: 'ビルトインエアコン', portals: ['A'] },
      { id: 'all_room_aircon', label: '全居室エアコン', portals: ['A'] },
      { id: 'ceiling_fan', label: 'シーリングファン', portals: ['A'] },
      { id: 'gas_heating', label: 'ガス暖房', portals: [] },
      { id: 'telework', label: 'テレワーク向け', portals: [] },
      { id: 'soundproof_room', label: '防音室あり', portals: [] },
    ],
  },
  {
    id: 'layout',
    label: '間取り',
    items: [
      { id: 'two_family', label: '2世帯住宅', portals: ['S'] },
      { id: 'japanese_room', label: '和室', portals: ['S'] },
      { id: 'movable_partition', label: '可動間仕切り', portals: ['S','A'] },
      { id: 'loft', label: 'ロフト', portals: ['S'] },
      { id: 'ldk15plus', label: 'LDK15畳以上', portals: ['S'] },
      { id: 'ldk18plus', label: 'LDK18畳以上', portals: ['S'] },
      { id: 'ldk20plus', label: 'LDK20畳以上', portals: ['S'] },
      { id: 'all_room_6tatami', label: '全居室6畳以上', portals: ['S'] },
      { id: 'atrium', label: '吹抜け', portals: ['S','A','Y'] },
      { id: 'basement', label: '地下室', portals: ['A'] },
      { id: 'living_15plus', label: 'リビングダイニング15畳以上', portals: ['Y'] },
    ],
  },
  {
    id: 'bathroom',
    label: '浴室',
    items: [
      { id: 'tv_bath', label: 'TV付浴室', portals: ['S','A'] },
      { id: 'jet_bath', label: 'ジェットバス', portals: ['S'] },
      { id: 'auto_bath', label: 'オートバス', portals: ['S','A'] },
      { id: 'bath_dryer', label: '浴室乾燥機', portals: ['S','A','Y'] },
      { id: 'reheat_bath', label: '追い炊き', portals: ['A'] },
      { id: 'bath_window', label: '浴室に窓', portals: ['S','A'] },
      { id: 'mist_sauna', label: 'ミストサウナ', portals: ['S','A'] },
      { id: 'audio_bath', label: 'オーディオバス', portals: ['S','A'] },
      { id: 'open_air_bath', label: '露天風呂', portals: ['S'] },
      { id: 'bath_1tsubo', label: '浴室1坪以上', portals: ['S','A'] },
      { id: 'bath_1tsubo_strong', label: '浴室1坪強以上（1.6×1.8m相当）', portals: [] },
      { id: 'bath_125tsubo', label: '浴室1.25坪（1.6x2.0m）以上', portals: [] },
      { id: 'bath_toilet_sep', label: 'バス・トイレ別', portals: [] },
      { id: 'full_auto_bath', label: 'フルオートバス', portals: [] },
      { id: 'high_temp_bath', label: '高温差湯式', portals: ['A'] },
      { id: 'changing_room', label: '脱衣所あり', portals: [] },
      { id: 'sauna', label: 'サウナ', portals: ['A'] },
      { id: 'bath_heating', label: '浴室暖房', portals: ['A'] },
      { id: 'shower_room', label: 'シャワールーム', portals: ['A'] },
    ],
  },
  {
    id: 'sunlight',
    label: '陽当たり・採光・通風',
    items: [
      { id: 'south_facing', label: '南向き', portals: ['S'] },
      { id: 'all_south', label: '全室南向き', portals: ['S'] },
      { id: 'all_2side_light', label: '全室2面採光', portals: ['S','A'] },
      { id: 'three_side_light', label: '3面採光', portals: ['S','A'] },
      { id: 'southeast_facing', label: '東南向き', portals: ['S'] },
      { id: 'southwest_facing', label: '南西向き', portals: ['S'] },
      { id: 'all_southeast', label: '全室東南向き', portals: ['S'] },
      { id: 'all_southwest', label: '全室南西向き', portals: ['S'] },
      { id: 'good_ventilation', label: '通風良好', portals: ['S'] },
      { id: 'good_sunlight', label: '陽当り良好', portals: ['S'] },
      { id: 'two_side_light', label: '2面採光', portals: ['A'] },
    ],
  },
  {
    id: 'storage',
    label: '収納',
    items: [
      { id: 'walk_in_closet', label: 'W.INクローゼット', portals: ['S','A','Y'] },
      { id: 'under_floor', label: '床下収納', portals: ['S','A','Y'] },
      { id: 'all_room_storage', label: '全居室収納', portals: ['S','A'] },
      { id: 'storeroom', label: '納戸', portals: ['S'] },
      { id: 'attic_storage', label: '屋根裏収納', portals: ['S'] },
      { id: 'storage', label: '収納', portals: [] },
      { id: 'closet', label: 'クローゼット', portals: ['A'] },
      { id: 'shed', label: '物置有', portals: [] },
      { id: 'shoes_closet', label: 'シューズインクローク', portals: ['S','A'] },
      { id: 'shoe_box', label: 'シューズボックス', portals: [] },
      { id: 'down_wall_storage', label: 'ダウンウォール収納', portals: ['A'] },
      { id: 'walk_through_closet', label: 'ウォークスルークローゼット', portals: ['A'] },
      { id: 'grenier', label: 'グルニエ', portals: ['A'] },
    ],
  },
  {
    id: 'kitchen',
    label: 'キッチン・関連設備',
    items: [
      { id: 'system_kitchen', label: 'システムキッチン', portals: ['S','A'] },
      { id: 'counter_kitchen', label: '対面式キッチン', portals: ['S','A','Y'] },
      { id: 'dishwasher', label: '食器洗乾燥機', portals: ['S','A','Y'] },
      { id: 'disposer', label: 'ディスポーザー', portals: ['S','A'] },
      { id: 'independent_kitchen', label: '独立キッチン', portals: ['A','Y'] },
      { id: 'gas_kitchen', label: 'ガスキッチン', portals: [] },
      { id: 'stove_1', label: 'コンロ1口', portals: [] },
      { id: 'stove_2', label: 'コンロ2口', portals: ['A'] },
      { id: 'stove_3', label: 'コンロ3口', portals: ['A'] },
      { id: 'stove_4plus', label: 'コンロ4口以上', portals: [] },
      { id: 'electric_stove', label: '電気コンロ', portals: [] },
      { id: 'pantry', label: 'パントリー', portals: ['S'] },
      { id: 'ih_cooker', label: 'IHクッキングヒータ', portals: ['S','A','Y'] },
      { id: 'water_purifier', label: '浄水器', portals: ['S','A'] },
      { id: 'oven', label: 'オーブン', portals: [] },
      { id: 'island_kitchen', label: 'アイランドキッチン', portals: ['S','A'] },
      { id: 'dish_dryer', label: '食器乾燥機', portals: ['A'] },
      { id: 'open_kitchen', label: 'オープンキッチン', portals: ['A'] },
      { id: 'type2_kitchen', label: 'Ⅱ型キッチン', portals: ['A'] },
      { id: 'twoway_kitchen', label: '2WAYキッチン', portals: ['A'] },
      { id: 'threeway_kitchen', label: '3WAYキッチン', portals: ['A'] },
      { id: 'grill', label: 'グリル', portals: ['A'] },
      { id: 'gas_oven', label: 'ガスオーブン', portals: ['A'] },
      { id: 'kitchen_floor_heating', label: 'キッチン床暖房', portals: ['A'] },
      { id: 'u_shape_kitchen', label: 'コの字（U字）型キッチン', portals: [] },
    ],
  },
  {
    id: 'tv_communication',
    label: 'テレビ・通信',
    items: [
      { id: 'internet_ready', label: 'インターネット対応', portals: ['A'] },
      { id: 'high_speed_internet', label: '高速インターネット', portals: ['S'] },
      { id: 'fiber_optic', label: '光ファイバー', portals: ['A','Y'] },
      { id: 'wired_broadcast', label: '有線放送', portals: [] },
      { id: 'catv', label: 'CATV', portals: ['S','A'] },
      { id: 'bs_antenna', label: 'BSアンテナ', portals: ['S','A'] },
      { id: 'cs_antenna', label: 'CSアンテナ', portals: ['S','A'] },
      { id: 'internet_fiber', label: 'インターネット光対応', portals: [] },
      { id: 'internet_broadband', label: 'インターネットブロードバンド', portals: [] },
      { id: 'internet_other', label: 'その他インターネット', portals: [] },
      { id: 'catv_internet', label: 'CATVインターネット', portals: ['A'] },
    ],
  },
  {
    id: 'reform',
    label: 'リフォーム・リノベーション',
    items: [
      { id: 'flooring_replace', label: 'フローリング張替', portals: ['S'] },
      { id: 'renovation', label: 'リノベーション', portals: ['S'] },
      { id: 'fit_renovation', label: '適合リノベーション', portals: ['S'] },
      { id: 'interior_reform', label: '内装リフォーム', portals: ['S'] },
      { id: 'exterior_reform', label: '外装リフォーム', portals: ['S'] },
      { id: 'full_reform', label: '内外装リフォーム', portals: ['S'] },
      { id: 'reformed', label: 'リフォーム済み', portals: ['S'] },
      { id: 'plumbing_5years', label: '5年以内に水回り設備交換', portals: [] },
      { id: 'interior_5years', label: '5年以内に内装リフォーム', portals: [] },
    ],
  },
  {
    id: 'balcony',
    label: 'バルコニー・テラス',
    items: [
      { id: 'wide_balcony', label: 'ワイドバルコニー', portals: ['S','A'] },
      { id: 'south_balcony', label: '南面バルコニー', portals: ['S'] },
      { id: 'roof_balcony', label: 'ルーフバルコニー', portals: ['S','A'] },
      { id: 'two_side_balcony', label: '2面以上バルコニー', portals: ['S'] },
      { id: 'balcony', label: 'バルコニー', portals: [] },
      { id: 'terrace', label: 'テラス', portals: [] },
      { id: 'wood_deck', label: 'ウッドデッキ', portals: ['S','A','Y'] },
      { id: 'balcony_faucet', label: 'バルコニー・屋上に水栓あり', portals: ['S'] },
    ],
  },
  {
    id: 'toilet_wash',
    label: 'トイレ・洗面関連設備',
    items: [
      { id: 'two_toilets', label: 'トイレ2ヶ所', portals: ['S','A','Y'] },
      { id: 'washlet', label: '温水洗浄便座', portals: ['S','A'] },
      { id: 'shampoo_dresser', label: 'シャワー付洗面台（シャンプードレッサー）', portals: ['S','A'] },
      { id: 'high_function_toilet', label: '高機能トイレ', portals: ['S'] },
      { id: 'heated_seat', label: '暖房便座', portals: [] },
      { id: 'independent_basin', label: '独立洗面台', portals: [] },
      { id: 'slop_sink', label: 'スロップシンク', portals: [] },
      { id: 'water_saving_toilet', label: '節水型トイレ', portals: ['S'] },
      { id: 'tankless_toilet', label: 'タンクレストイレ', portals: ['A'] },
    ],
  },
  {
    id: 'garden',
    label: '庭',
    items: [
      { id: 'south_garden', label: '南庭', portals: ['S'] },
      { id: 'private_garden', label: '専用庭', portals: ['S'] },
      { id: 'garden_10tsubo', label: '庭10坪以上', portals: ['S','A'] },
      { id: 'garden_10sqm', label: '10㎡以上の庭', portals: [] },
      { id: 'garden', label: '庭', portals: ['S','A'] },
    ],
  },
  {
    id: 'view',
    label: '眺望・自然環境',
    items: [
      { id: 'ocean_view', label: 'オーシャンビュー', portals: ['S'] },
      { id: 'near_sea', label: '海まで2km以内', portals: ['S','Y'] },
      { id: 'riverside', label: 'リバーサイド', portals: ['S'] },
      { id: 'rural_view', label: '田園風景', portals: ['S'] },
      { id: 'fireworks_view', label: '花火大会鑑賞', portals: ['S'] },
      { id: 'good_view', label: '眺望良好', portals: ['S'] },
      { id: 'lake_view', label: '湖・池が見える', portals: ['S'] },
      { id: 'mountain_view', label: '山が見える', portals: ['S'] },
    ],
  },
  {
    id: 'parking',
    label: '駐車・駐輪・室外設備',
    items: [
      { id: 'parking_2cars', label: '駐車2台可', portals: ['S','A','Y'] },
      { id: 'parking_3plus', label: '駐車3台以上可', portals: ['S','A'] },
      { id: 'shutter_garage', label: 'シャッター車庫', portals: ['S'] },
      { id: 'built_in_garage', label: 'ビルドガレージ', portals: ['S','Y'] },
      { id: 'snow_melt', label: '融雪対策', portals: ['S'] },
      { id: 'field', label: '畑', portals: ['S'] },
      { id: 'vegetable_garden', label: '家庭菜園', portals: ['S'] },
      { id: 'road_heater', label: 'ロードヒーター', portals: ['A'] },
      { id: 'interphone', label: 'インターホン', portals: [] },
      { id: 'parking', label: '駐車場', portals: [] },
      { id: 'rooftop', label: '屋上', portals: ['S'] },
      { id: 'high_roof_parking', label: 'ハイルーフ駐車場', portals: [] },
      { id: 'ev_charger', label: 'EV車充電設備', portals: ['S','A'] },
      { id: 'electric_shutter', label: '電動シャッター', portals: ['A'] },
      { id: 'sunroom', label: 'サンルーム', portals: ['A'] },
      { id: 'engawa', label: '縁側', portals: ['A'] },
      { id: 'garage', label: 'ガレージ', portals: [] },
    ],
  },
  {
    id: 'surroundings',
    label: '周辺環境',
    items: [
      { id: 'wide_gap', label: '隣の建物との間隔が広い', portals: ['S'] },
      { id: 'low_traffic', label: '周辺交通量が少なめ', portals: ['S'] },
      { id: 'good_sidewalk', label: '整備された歩道', portals: ['S'] },
      { id: 'near_golf', label: 'ゴルフ場が近い', portals: ['S'] },
      { id: 'near_ski', label: 'スキー場が近い', portals: ['S'] },
      { id: 'near_tennis', label: 'テニスコートが近い', portals: ['S'] },
      { id: 'express_station', label: '急行停車駅', portals: [] },
      { id: 'elem_school_10min', label: '小学校徒歩10分以内', portals: ['S'] },
      { id: 'mid_school_10min', label: '中学校徒歩10分以内', portals: [] },
      { id: 'convenience_5min', label: 'コンビニ徒歩5分以内', portals: [] },
      { id: 'supermarket_10min', label: 'スーパー徒歩10分以内', portals: ['S'] },
      { id: 'hospital_10min', label: '総合病院10分以内', portals: ['S'] },
      { id: 'park_800m', label: '公園800m以内', portals: [] },
      { id: 'elem_school_1km', label: '小学校まで1km以内', portals: ['Y'] },
    ],
  },
  {
    id: 'structure',
    label: '建物構造',
    items: [
      { id: 'earthquake_resistant', label: '耐震構造', portals: ['Y'] },
      { id: 'seismic_isolation', label: '免震構造', portals: ['A','Y'] },
      { id: 'vibration_control', label: '制震構造', portals: ['A','Y'] },
      { id: 'outer_insulation', label: '外断熱', portals: ['A','Y'] },
      { id: 'long_life_housing', label: '長期優良住宅', portals: ['S','Y'] },
      { id: 'low_carbon', label: '低炭素住宅', portals: ['S','A'] },
      { id: 'completion_inspection', label: '建築後の完了検査済証あり', portals: ['S','A'] },
      { id: 'seismic_cert', label: '耐震基準適合証明書あり', portals: ['S'] },
      { id: 'inspection_done', label: 'インスペクション（建物検査）済み', portals: [] },
      { id: 'original_design', label: '新築時・増改築時の設計図あり', portals: ['S'] },
      { id: 'warranty_gov', label: '瑕疵保険（国交省指定法人）による保証', portals: ['S','A'] },
      { id: 'warranty_company', label: '瑕疵保険（不動産会社独自）による保証', portals: ['S','A'] },
      { id: 'design_performance', label: '設計住宅性能評価付', portals: ['S','A','Y'] },
      { id: 'construction_performance', label: '建築住宅性能評価付', portals: ['S','A','Y'] },
      { id: 'dual_family', label: '二世帯向き', portals: ['A','Y'] },
      { id: 'housing_warranty', label: '住宅性能保証書', portals: [] },
      { id: 'maintenance_record', label: '修繕・点検の記録', portals: ['S','A'] },
      { id: 'tile_exterior', label: 'タイル張り', portals: [] },
      { id: 'designer', label: 'デザイナーズ', portals: ['A'] },
      { id: 'compliance_report', label: '法適合状況調査報告書', portals: ['S'] },
      { id: 'defect_insurance_check', label: '瑕疵保険検査基準適合', portals: ['A'] },
      { id: 'architect_report', label: '建築士等の建物検査報告書', portals: ['S'] },
      { id: 'long_life_cert', label: '長期優良住宅認定通知書', portals: [] },
      { id: 'safe_r_housing', label: '安心R住宅', portals: ['A'] },
      { id: 'layout_changeable', label: '間取り変更可能', portals: ['Y'] },
      { id: 'full_flat_floor', label: 'フルフラットフロア', portals: ['Y'] },
      { id: 'bels', label: 'BELS/省エネ基準適合認定書あり', portals: ['S','A'] },
      { id: 'log_house', label: 'ログハウス', portals: ['S'] },
      { id: 'old_style', label: '古民家風', portals: ['S'] },
      { id: 'warranty_usable', label: '瑕疵保険（国交省指定）保証利用可', portals: ['S'] },
      { id: '2x4', label: '2×4工法', portals: [] },
      { id: '2x6', label: '2×6工法', portals: ['A'] },
      { id: 'outframe', label: 'アウトフレーム工法', portals: ['A'] },
      { id: 'inverted_beam', label: '逆梁工法', portals: ['A'] },
      { id: 'skeleton_infill', label: 'スケルトンインフィル', portals: ['A'] },
      { id: 'non_formaldehyde', label: 'ノンホルムアルデヒド', portals: ['A'] },
      { id: 'concrete_exterior', label: '外壁コンクリート', portals: ['A'] },
      { id: 'concrete_interior', label: '内装コンクリート', portals: ['A'] },
      { id: 'siding_exterior', label: '外壁サイディング', portals: ['A'] },
      { id: 'high_sash', label: 'ハイサッシ採用', portals: ['A'] },
      { id: 'smart_house', label: 'スマートハウス', portals: ['A'] },
      { id: 'design_document', label: '新築・増改築設計図書', portals: ['A'] },
      { id: 'bungalow', label: '平屋', portals: [] },
      { id: 'no_snow_roof', label: '無落雪屋根', portals: [] },
    ],
  },
  {
    id: 'common_area',
    label: '共用部',
    items: [
      { id: 'pool', label: 'プール', portals: ['S'] },
      { id: 'common_outdoor_bath', label: '共用露天風呂', portals: ['S'] },
      { id: 'elevator', label: 'エレベータ', portals: ['A'] },
      { id: 'guest_room', label: 'ゲストルーム', portals: [] },
    ],
  },
  {
    id: 'land',
    label: '立地・土地特徴',
    items: [
      { id: 'hilltop', label: '高台に立地', portals: ['S'] },
      { id: 'land_readjustment', label: '区画整理地内', portals: ['S','A'] },
      { id: 'regular_shaped', label: '整形地', portals: ['S','A'] },
      { id: 'green_area', label: '緑豊かな住宅地', portals: ['S'] },
      { id: 'quiet_area', label: '閑静な住宅地', portals: ['S','A'] },
      { id: 'flat_land', label: '平坦地', portals: ['S','Y'] },
      { id: 'no_front_building', label: '前面棟無', portals: ['S','A'] },
      { id: 'corner_lot', label: '角地', portals: ['S'] },
      { id: 'large_development', label: '大型タウン内', portals: ['S'] },
      { id: 'summer_resort', label: '避暑地', portals: ['S'] },
      { id: 'near_city', label: '都市近郊', portals: ['S'] },
      { id: 'development_area', label: '開発分譲地内', portals: ['S','A','Y'] },
      { id: 'ground_survey', label: '地盤調査済', portals: ['S'] },
      { id: 'land_50tsubo', label: '土地50坪以上', portals: ['S'] },
      { id: 'land_100tsubo', label: '土地100坪以上', portals: ['S'] },
      { id: 'south_road', label: '南側道路面す', portals: ['S','Y'] },
      { id: 'road_6m', label: '前道6m以上', portals: ['S','Y'] },
      { id: 'near_downtown', label: '市街地が近い', portals: ['S'] },
      { id: 'hot_spring', label: '温泉付', portals: ['S'] },
      { id: 'hot_spring_available', label: '温泉引き込み可', portals: ['S'] },
      { id: 'adjacent_distance', label: '隣接建物距離2m以上', portals: ['A'] },
      { id: 'no_rebuild', label: '再建築不可', portals: ['A'] },
    ],
  },
  {
    id: 'station',
    label: '駅利便性',
    items: [
      { id: 'flat_to_station', label: '駅まで平坦', portals: ['S'] },
      { id: 'first_station', label: '始発駅', portals: ['S','Y'] },
      { id: 'two_lines', label: '2沿線以上利用可', portals: ['S'] },
    ],
  },
  {
    id: 'conditions',
    label: '費用・引き渡し・入居・条件',
    items: [
      { id: 'immediate_occupancy', label: '即入居可', portals: ['S'] },
      { id: 'fiscal_year_occupancy', label: '年度内入居可', portals: ['S'] },
      { id: 'year_end_occupancy', label: '年内入居可', portals: ['S'] },
      { id: 'immediate_delivery', label: '即引渡し可', portals: [] },
      { id: 'pet_negotiable', label: 'ペット相談', portals: ['A'] },
      { id: 'building_10yr_warranty', label: '建物10年保証', portals: [] },
      { id: 'flat35', label: 'フラット35対応', portals: [] },
      { id: 'flat35s', label: 'フラット35S対応', portals: ['S'] },
      { id: 'flat35_eligible', label: 'フラット35適合', portals: [] },
      { id: 'flat35s_eligible', label: 'フラット35S適合', portals: [] },
      { id: 'flat35_s_eligible', label: 'フラット35・S適合', portals: ['S'] },
      { id: 'vacant_house_bank', label: '空き家バンク登録物件', portals: ['S','A'] },
      { id: 'customizable', label: 'カスタマイズ可', portals: [] },
      { id: 'free_design', label: '自由設計対応', portals: [] },
      { id: 'elderly_only', label: '高齢者限定', portals: [] },
      { id: 'elderly_welcome', label: '高齢者歓迎', portals: [] },
    ],
  },
  {
    id: 'security',
    label: '管理・セキュリティ',
    items: [
      { id: 'tv_interphone', label: 'TVドアホン', portals: ['S','A','Y'] },
      { id: 'card_key', label: 'カードキー', portals: ['A'] },
      { id: 'dimple_key', label: 'ディンプルキー', portals: ['A'] },
      { id: 'security_24h', label: '24時間セキュリティ', portals: ['A','Y'] },
      { id: 'security_glass', label: '防犯用ガラス', portals: ['A'] },
      { id: 'security_camera', label: '防犯カメラ', portals: ['A','Y'] },
      { id: 'security_enhanced', label: 'セキュリティ充実', portals: ['S'] },
      { id: 'smart_key', label: 'スマートキー', portals: ['S'] },
      { id: 'double_lock', label: 'ダブルロックドア', portals: ['A'] },
    ],
  },
  {
    id: 'eco',
    label: 'エコ関連',
    items: [
      { id: 'all_electric', label: 'オール電化', portals: ['S','A','Y'] },
      { id: 'solar_power', label: '太陽光発電システム', portals: ['S','A','Y'] },
      { id: 'double_glazing', label: '複層ガラス', portals: ['S','A'] },
      { id: 'eco_water_heater', label: '省エネ給湯器', portals: ['S','A'] },
      { id: 'durable_eco', label: '高耐久省エネ住宅', portals: [] },
      { id: 'energy_saving', label: '省エネルギー対策', portals: ['S'] },
      { id: 'high_insulation', label: '高気密高断熱住宅', portals: ['S','A'] },
      { id: 'eco_point', label: 'エコポイント対象住宅', portals: ['S'] },
      { id: 'battery', label: '蓄電池', portals: ['A','Y'] },
      { id: 'hems', label: 'HEMS（ホームエネルギーマネジメントシステム）', portals: ['Y'] },
      { id: 'fuel_cell', label: '家庭用燃料電池', portals: [] },
      { id: 'triple_glazing', label: '三層複層ガラス', portals: ['A'] },
      { id: 'low_e_glass', label: 'Low-Eガラス', portals: ['A'] },
    ],
  },
];

// featuresの全idリストを取得するヘルパー
export const getAllFeatureIds = (): string[] =>
  PROPERTY_FEATURES.flatMap(cat => cat.items.map(item => item.id));

// idからラベルを取得するヘルパー
export const getFeatureLabel = (id: string): string => {
  for (const cat of PROPERTY_FEATURES) {
    const item = cat.items.find(i => i.id === id);
    if (item) return item.label;
  }
  return id;
};
