-- Add address display, geocoding, seller info, transport, and extended fields
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "address_display_level"   TEXT NOT NULL DEFAULT 'town';
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "address_display_custom"  TEXT;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "town"                    TEXT;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "building_name"           TEXT;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "room_number"             TEXT;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "latitude"                DOUBLE PRECISION;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "longitude"               DOUBLE PRECISION;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "price_negotiable"        BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "ad_transfer_consent"     TEXT NOT NULL DEFAULT 'あり';
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "bus_stop1"               TEXT;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "bus_time1"               INTEGER;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "bus_stop2"               TEXT;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "bus_time2"               INTEGER;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "bus_stop3"               TEXT;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "bus_time3"               INTEGER;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "rooms_count"             INTEGER;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "ldk_size"                DOUBLE PRECISION;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "road_direction"          TEXT;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "road_contact"            TEXT;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "building_conditions"     BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "rebuild_allowed"         TEXT;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "national_land_act"       BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "agricultural_act"        BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "landscape_act"           BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "delivery_condition"      TEXT;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "reins_updated_at"        TIMESTAMP(3);
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "reins_status"            TEXT;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "seller_company"          TEXT;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "seller_contact"          TEXT;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "seller_agent"            TEXT;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "seller_transaction_type" TEXT;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "seller_brokerage_type"   TEXT;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "purchase_price"          INTEGER;
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "purchase_date"           TIMESTAMP(3);
